product: 'QuestionEngine.API'
application_name: 'QuestionEngine.API'

version:
  major: '1'
  minor: '0'

pickled:
  living_docs: &living_docs
    command: '../rake-tools/Pickles.CommandLine/Pickles.exe'
    log: '../rake-tools/Pickles.CommandLine/pickle.log'
    folder: './test/QuestionEngine.API.AcceptanceTests/LivingDocumentation'
    format: 'DHtml'
    destination:
      server: 'qa15.ad.laterooms.com'
      share: 'd$'
      path: 'QuestionEngine.API\Applications\LivingDocumentation\LivingDocumentation'
  wip:
    <<: *living_docs
    folder: './test/QuestionEngine.API.AcceptanceTests/Features'
    destination:
      server: 'qa15.ad.laterooms.com'
      share: 'd$'
      path: 'QuestionEngine.API\Applications\LivingDocumentation\WIP'

archive:
  directories: [ "parameters", "rake-files" ]
  files: ["config.env.yml", "config.featureswitches.yml", "Gemfile", "Gemfile.lock", "generic_rakefile.rb", "rakefile.rb"]

dir:
  build: 'build'
  build_artifacts: 'build-artifacts'
  archive: 'config-management'
  nuget_package: 'nuget-package'
  parameters: 'parameters'
  rake_tools: '../rake-tools'
  test_results: 'TestResults'
  ms_deploy: '../rake-tools/msdeploy-3.0'
  deployment_scripts: 'deployment-scripts'
  statuschecker:
    package: 'build-artifacts/Infrastructure.Service.StatusChecker.MsDeployPackage'
    versions_to_monitor: [ '1.0' ]

env:
  telfordlive:
    blue: &telfordblue
      deploy_drive: 'd:/'
      app_pool_username: 'TLRG\svc_keyword_api'
      app_pool_password: 'Manchester01'
      connection_string: 'Server=NEWDBS016P;Database=laterooms;connection timeout=30;Integrated Security=SSPI;'
      hostname: 'keyword.api.laterooms.com'
      servers: [{ :server: 'TELAPP441P.tlrg.org' }, { :server: 'TELAPP442P.tlrg.org' }]	  
      msdeploy_port: 89
      monitoring:
        logstash_ipaddress: '172.31.164.123'
        logstash_port: 112
        logstash_enabled: true
    green:
      <<: *telfordblue
      servers: [{ :server: 'TELAPP443P.tlrg.org' }, { :server: 'TELAPP444P.tlrg.org' }]

  sandbox:
    app_pool_username: 'TLRG\svc_keyword_api'
    app_pool_password: 'Manchester01'
    connection_string: 'Server=TELDBS016P;Database=laterooms;connection timeout=30;Integrated Security=SSPI;'
    deploy_drive: 'd:/'
    hostname: 'keyword.api.sandbox.laterooms.com'
    servers: [ { :server: 'TELAPP438S.tlrg.org' } ]
    msdeploy_port: 89
    monitoring:
      logstash_ipaddress: '127.0.0.1'
      logstash_port: 112
      logstash_enabled: true

  qa:
    app_pool_username: 'AD\svc_keyword_api'
    app_pool_password: 'Manchester01'
    connection_string: 'Server=DBTEST01;Database=laterooms;connection timeout=30;Integrated Security=SSPI;'
    deploy_drive: 'd:/'
    hostname: 'api.keyword.qa.ad.laterooms.com'
    servers: [ { :server: 'TELTLRGSRQA07.ad.laterooms.com' }, { :server: 'TELTLRGSRQA02.ad.laterooms.com' } ]
    monitoring:
      logstash_ipaddress: '172.31.168.40'
      logstash_port: 112
      logstash_enabled: true

  ci: &ci
    app_pool_username: 'AD\svc_keyword_api'
    app_pool_password: 'Manchester01'
    connection_string: 'Server=DBDEV01;Database=laterooms;connection timeout=30;Integrated Security=SSPI;'
    deploy_drive: 'd:/'
    hostname: 'api.keyword.ci.ad.laterooms.com'
    servers: [ { :server: 'qa15.ad.laterooms.com' } ]
    monitoring:
      logstash_ipaddress: '127.0.0.1'
      logstash_port: 112
      logstash_enabled: true

  dev:
    <<: *ci
    deploy_drive: 'c:/'
    hostname: 'api.QuestionEngine.local'
    servers: [ { :server: 'localhost' } ]
